/** Centralized route paths — import and reference instead of hardcoding string literals. */
export const ROUTES = {
  home: "/",
  products: "/products",
  sorg: "/sorg",
  checkout: "/checkout",
  about: "/about",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  setupAccount: "/setup-account",
  feedback: "/feedback",
  settings: "/settings",
  admin: {
    dashboard: "/admin",
    users: "/admin/users",
    usersAdd: "/admin/users/add",
    products: "/admin/products",
    groups: "/admin/groups",
    group: (groupId: string) => `/admin/groups/${groupId}`,
    voiceSession: (roomId: string) => `/admin/voice/${roomId}`,
    uiComponents: "/admin/ui-components",
    testing: "/admin/testing",
  },
  customer: {
    dashboard: "/customer",
    sorg: "/customer/sorg",
    billing: "/customer/billing",
    gamers: "/customer/gamers",
    groups: "/customer/groups",
    group: (groupId: string) => `/customer/groups/${groupId}`,
  },
  gamer: {
    dashboard: "/gamer",
    groups: "/gamer/groups",
    group: (groupId: string) => `/gamer/groups/${groupId}`,
    voiceSession: (roomId: string) => `/gamer/voice/${roomId}`,
  },
  gedu: {
    dashboard: "/gedu",
    groups: "/gedu/groups",
    group: (groupId: string) => `/gedu/groups/${groupId}`,
    voiceSession: (roomId: string) => `/gedu/voice/${roomId}`,
  },
} as const;
