"use client";

import { Star } from "lucide-react";
import { useTranslations } from "next-intl";
import { cn } from "@/lib/utils";
import { newcomerDaysIn, NEWCOMER_WINDOW_DAYS } from "./newcomer";

/**
 * The staff-only "new to this group" badge — a small pill beside a member's
 * name that says how recently they joined (see ./newcomer.ts for the clock).
 *
 * It renders for Gedus and admins only, and that gate is *data*, not a viewer
 * prop: `joinedAt` comes from staff-scoped reads, so a surface a family sees
 * simply never has a value to pass. Rendering `null` past the window (or for
 * a `null` stamp) keeps every call site a bare one-liner.
 *
 * `now` is the caller's, not this component's: every surface that shows the
 * badge already carries a request-stable clock (a scene's frozen instant, the
 * feed's `feedNow`), and a badge reading its own `new Date()` would disagree
 * with the page around it and drift between SSR and hydration.
 *
 * **The glyph is a star.** A sprout shipped first and collided twice — it is
 * the beginner product tag's chip icon and one of the voice-zone icons a
 * moderator can pick, so a Gedu could meet three sprouts meaning three
 * different things in one viewport. A sparkle was the obvious replacement and
 * was rejected: it now reads industry-wide as *generated by AI*, which is not a
 * thing to imply about a child.
 */
export function NewcomerBadge({
  joinedAt,
  now,
  className,
}: {
  joinedAt: string | null | undefined;
  now: Date;
  className?: string;
}) {
  const t = useTranslations("memberFlair");
  const days = newcomerDaysIn(joinedAt, now);
  if (days === null) return null;

  return (
    <span
      title={t("newcomerTooltip", { days })}
      className={cn(
        "inline-flex shrink-0 items-center gap-1 rounded-full border border-success/40 bg-success/15 px-1.5 py-0 text-[10px] font-medium leading-4 text-success",
        className,
      )}
    >
      <Star className="h-3 w-3" aria-hidden />
      {t("newcomer")}
      <WeekMeter days={days} />
    </span>
  );
}

/**
 * Four pips at the pill's end, one spent per week of the window.
 *
 * **This is how the badge spends its month, and it is a meter rather than a
 * fade for a reason.** The first version faded the whole pill from full opacity
 * down to a floor, which turned out to be unreadable in the only place it
 * mattered: a badge at two-thirds opacity means nothing unless there is a
 * full-strength one beside it to compare against, and a roster of eight rarely
 * offers one. A meter is countable from a single row.
 *
 * **Laid out 2×2 rather than in a line.** A row of four pips is nearly as wide
 * as the word beside it, and on a 360px participant row that is width the name
 * needs; a square block is a quarter of that and reads as one object rather
 * than as four things to count. It also drains like a block — the bottom right
 * goes first and the top left is the last to survive — so the shape itself
 * changes as the month passes,
 * which a line of dimming dots does not do nearly as visibly.
 *
 * The decorative half of the badge — the tooltip already carries the exact age,
 * and a screen reader gets the badge's word plus that title — so it is hidden
 * rather than described. Four buckets over thirty days means each pip is 7.5
 * days, which is why the arithmetic divides by the window rather than by seven:
 * a plain week count would produce a fifth pip on the window's last two days.
 */
function WeekMeter({ days }: { days: number }) {
  const PIPS = 4;
  const spent = Math.min(
    PIPS - 1,
    Math.floor((days / NEWCOMER_WINDOW_DAYS) * PIPS),
  );

  return (
    <span className="ml-1 grid grid-cols-2 gap-0.5" aria-hidden>
      {Array.from({ length: PIPS }, (_, index) => (
        <span
          key={index}
          className={cn(
            "h-1 w-1 rounded-full",
            index < PIPS - spent ? "bg-success" : "bg-success/25",
          )}
        />
      ))}
    </span>
  );
}
