import {
  BookOpen,
  Calendar,
  CircleCheck,
  Clock,
  Gamepad2,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  Laptop,
  Leaf,
  Lightbulb,
  MapPin,
  MessageCircle,
  Palette,
  Puzzle,
  Rocket,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Target,
  Trophy,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { LandingIcon } from "@/lib/landing-pages/sections";

/**
 * The lucide glyph of every icon a point may carry — exhaustive, so an icon
 * added to the curated list fails type-check here until it can be drawn. The
 * public page and the admin editor both draw from this one map.
 */
export const LANDING_ICON_GLYPHS: Record<LandingIcon, LucideIcon> = {
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  "shield-check": ShieldCheck,
  users: Users,
  "gamepad-2": Gamepad2,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "map-pin": MapPin,
  calendar: Calendar,
  clock: Clock,
  trophy: Trophy,
  rocket: Rocket,
  lightbulb: Lightbulb,
  "message-circle": MessageCircle,
  smile: Smile,
  puzzle: Puzzle,
  globe: Globe,
  laptop: Laptop,
  "circle-check": CircleCheck,
  palette: Palette,
  handshake: Handshake,
  target: Target,
  leaf: Leaf,
};
