-- Game Studio joins product_topic, on the label-only side of the enum.
--
-- It names subject matter rather than a piece of software — a group builds its
-- own game, and which engine or tool that takes is a fact about the individual
-- product, not about the topic. So it follows Creator Studio exactly: an entry
-- in src/lib/products/topics.ts carrying a literal label and no `info` block,
-- which is what makes the product page skip the "About X" card (and its grid
-- wrapper) rather than render a generic one at the wrong altitude. What a
-- family needs in order to take part is written per product into that
-- product's own description, where it can differ between two Game Studio
-- products.
--
-- The label is an English literal like every other topic label, and Game
-- Studio is School of Gaming's own name for the programme — a proper noun, so
-- the never-translated rule applies to it for the same reason it applies to
-- Creator Studio rather than for the reason it applies to Programming or AI.
--
-- ADD VALUE appends to the end of the enum. That ordinal is meaningless here:
-- display order is a hand-maintained tuple in src/lib/products/topics.ts,
-- precisely because the enum's own order is just the order values were added.
-- IF NOT EXISTS keeps a re-run harmless, and no statement below reads the new
-- value, so this stays safe to apply inside a transaction.

ALTER TYPE public.product_topic ADD VALUE IF NOT EXISTS 'game_studio';
