import { ROUTES } from "@/lib/constants";
import type { ProductStatus, ProductType } from "@/types";
import type {
  AdminDashboardData,
  ComingUpCohort,
  ComingUpDay,
  ComingUpItem,
  ProductAttention,
  ProductIssue,
  ProductIssueKind,
  ScheduleChip,
  ScheduleWeek,
  UncertifiedGedu,
} from "./admin-dashboard-data";
import { addCalendarDays, mondayOf, monthsAfter, weekdayOf } from "./calendar";
import { PRODUCT_TYPE_ORDER } from "./product-type-presentation";

/**
 * Fixtures for the admin dashboard preview scene: a plausible autumn term for a
 * platform running sixty products, and the ops queue that comes with it.
 *
 * **Everything here is deterministic.** No `Math.random`, no `Date.now`, no
 * `crypto.randomUUID` at module load or at render — a fixture that changes
 * between two reloads makes a design impossible to compare with itself, and an
 * identicon built from a fresh UUID gives the same person a different face every
 * time the page is opened. The clock is a single pinned instant (below), the
 * product set is generated by index-keyed loops over literal name lists, and
 * every person id is a real UUID pasted in as a literal.
 *
 * **The schedule and the coming-up feed are resolved here, not in the body.** A
 * week's chips are the occurrences that actually fall in it — a term that has
 * not started, one that has ended and a club paused for syysloma all contribute
 * nothing — and the feed's cohorts are already grouped by date and type. That is
 * the same split the live page will want: the aggregation is a query's job, and
 * swapping this module for one is the whole of promotion.
 */

/**
 * **Two scenarios**, and they cannot coexist: an empty queue and a full one are
 * the same components in their two states.
 *
 * `busy` is the platform under real load — sixty products, twenty-one of them
 * needing something, five gedus waiting on a decision. `quiet` is six products
 * with nothing wrong anywhere, which is the only way to see the all-clear state
 * on a page that is otherwise doing its job.
 */
export const ADMIN_DASHBOARD_SCENARIOS = ["busy", "quiet"] as const;

export type AdminDashboardScenario =
  (typeof ADMIN_DASHBOARD_SCENARIOS)[number];

export function isAdminDashboardScenario(
  value: string,
): value is AdminDashboardScenario {
  return (ADMIN_DASHBOARD_SCENARIOS as readonly string[]).includes(value);
}

/**
 * The zone every product in this fixture is authored in.
 *
 * Products are written in Helsinki time and their schedule slots are wall clocks
 * there, so the weekday rows are Helsinki rows: a session at 17:00 sits at 17:00
 * whoever is reading. That is the admin surface's deliberate choice — an admin is
 * checking a schedule they authored, not attending a session — and it is why
 * nothing on this page converts to a viewer zone.
 */
export const ADMIN_DASHBOARD_TIMEZONE = "Europe/Helsinki";

/**
 * The pinned "now": Monday 17 August 2026, mid-morning in Helsinki.
 *
 * A *fixed* instant rather than the real clock, unlike the dashboards' scenes
 * next door, and the reason is that this page is a calendar. Week navigation
 * steps through a fixed range, one week is deliberately a holiday break, and the
 * coming-up feed is built to show a term boundary landing on one date; all of
 * that is arithmetic against a known Monday, and re-deriving it from a live clock
 * would make the scene show a different set of cases every day and none of them
 * the ones the design was drawn for. The cost is honest and known: this date will
 * one day be in the past, at which point the fixture is showing a historical term
 * rather than rotting silently.
 */
export const ADMIN_DASHBOARD_NOW = new Date("2026-08-17T09:20:00+03:00");

/** Today, as the bare calendar date it is in the schedule's own zone. */
const TODAY = "2026-08-17";

/** How many weeks either side of today the week view can be stepped through. */
const WEEKS_BEFORE = 2;
const WEEKS_AFTER = 15;

/**
 * How far the coming-up feed looks: the rest of this month plus three more.
 *
 * A calendar boundary rather than a day count, so the feed never ends by slicing
 * a term boundary in half at an arbitrary cutoff. From the pinned Monday it runs
 * to the end of November, which is where the school term's last day sits.
 */
const COMING_UP_MONTHS = 4;

/**
 * Real UUIDs for every person a fixture row names.
 *
 * They are literals, generated once, because the identicon beside a name is
 * hashed out of the id's hex bytes: a readable stand-in like `"gedu-aino"` does
 * not render a *different* face, it renders a degenerate one, which would make
 * every avatar in the scene a false picture of the real thing. Generating them
 * at load time would be worse still — the same gedu would wear a new face on
 * every reload, and no two screenshots would match.
 *
 * The readable name lives in the key so the rows below stay legible.
 */
const PERSON_IDS = {
  venlaSalminen: "38763617-b031-49af-9fd4-3320e7509019",
  topiasJarvinen: "88015a8b-5919-4d14-8a5e-31f538d181ae",
  iidaLehtonen: "e979b9eb-39a2-4b71-9aa1-3d991969dadc",
  onniRantanen: "66076d29-cdcb-4337-aa06-6cbb8e1b39de",
  helmiKoskinen: "4889fea4-0602-438f-adfe-2cef72d485ff",
} as const;

/** One product row, in the vocabulary the database actually stores. */
interface ProductSpec {
  id: string;
  name: string;
  productType: ProductType;
  /**
   * Internal to the fixture, and never surfaced to the body: nothing on the
   * dashboard displays a product's status any more. It survives here because
   * resolution needs it — a cancelled or completed run has no occurrences
   * whatever its slots still say, and a completed camp sitting in last week's
   * rows would be a lie the schedule told about itself.
   */
  status: ProductStatus;
  startDate: string;
  endDate: string | null;
  /** `null` is uncapped — not "no seats". */
  seatCount: number | null;
  activeCount: number;
  slots: readonly {
    /** 0 = Monday … 6 = Sunday. */
    weekday: number;
    startTime: string;
    durationMinutes: number;
  }[];
  /**
   * Mondays this product does not run, as bare calendar dates.
   *
   * Modelled because a resolved week has to be able to say "absent on purpose".
   * A school club is closed for syysloma, and a week where four of them vanish
   * with no explanation is indistinguishable from a week where four of them were
   * deleted.
   */
  breakWeeks: readonly string[];
}

// ---------------------------------------------------------------------------
// The catalogue
// ---------------------------------------------------------------------------

const CONSUMER_CLUB_NAMES = [
  "Minecraft-klubi Espoo",
  "Fortnite Club Tapiola",
  "Roblox Studio -klubi Kamppi",
  "Rocket League -klubi Leppävaara",
  "Minecraft Creative Club Kallio",
  "Valorant-klubi Töölö",
  "Among Us -klubi Herttoniemi",
  "Terraria-klubi Munkkiniemi",
  "Stardew Valley -klubi Vallila",
  "Roblox-klubi Matinkylä",
  "Minecraft Redstone Club Pasila",
  "Fortnite Creative Club Otaniemi",
  "Splatoon-klubi Käpylä",
  "Rocket League Academy Vuosaari",
  "Minecraft Survival Club Malmi",
  "Roblox Studio Advanced Punavuori",
  "Fortnite Club Lauttasaari",
  "Minecraft-klubi Kannelmäki",
  "Sims-klubi Sörnäinen",
  "Roblox-klubi Itäkeskus",
  "Minecraft Modding Club Arabianranta",
  "Fortnite Club Konala",
  "Rocket League -klubi Pitäjänmäki",
  "Minecraft-klubi Viikki",
  "Roblox Obby Club Oulunkylä",
] as const;

const MUNICIPALITY_CLUB_NAMES = [
  "Minecraft-kerho Tapiolan koulu",
  "Roblox-kerho Otaniemen lukio",
  "Pelikerho Leppävaaran koulu",
  "Minecraft-kerho Kalasataman peruskoulu",
  "Roblox-kerho Kaitaan koulu",
  "Pelikerho Hakunilan koulu",
  "Minecraft-kerho Tikkurilan koulu",
  "Roblox-kerho Myyrmäen koulu",
  "Pelikerho Kirkkonummen keskuskoulu",
  "Minecraft-kerho Nurmijärven yhteiskoulu",
  "Roblox-kerho Järvenpään Kartano",
  "Pelikerho Keravan Sompio",
  "Minecraft-kerho Porvoon Linnankoski",
  "Roblox-kerho Lohjan Anttila",
  "Pelikerho Hyvinkään Vehkoja",
  "Minecraft-kerho Tuusulan Hyrylä",
  "Roblox-kerho Sipoon Nikkilä",
  "Pelikerho Vihdin Nummela",
  "Minecraft-kerho Riihimäen Pohjoinen",
  "Roblox-kerho Mäntsälän Ehnroos",
] as const;

/**
 * Weekday rotations, weighted towards the middle of the week.
 *
 * Real weeks are not flat — Tuesday to Thursday is when families can get a child
 * to a club, and rows built on an even spread would hide the one thing stacking
 * seven of them is for. The rotation is a literal list rather than a modulus so
 * the weighting is visible at a glance and reproducible exactly.
 */
const PRIMARY_WEEKDAYS = [1, 2, 3, 0, 2, 1, 3, 4, 2, 1, 3, 2, 0, 3, 1, 2, 4, 1, 3, 2];

/** The second weekday of a twice-weekly club — never the same as the first. */
function secondWeekday(primary: number): number {
  return (primary + 2) % 5;
}

const CLUB_START_TIMES = ["16:00", "16:30", "17:00", "17:30", "18:00", "18:30"];
const CLUB_DURATIONS = [60, 90, 90, 60, 90, 75];
const CONSUMER_SEATS = [12, 16, 20, 14];
const CONSUMER_ACTIVE = [12, 9, 16, 7, 14, 11, 5, 18, 10, 13];
const MUNICIPALITY_SEATS = [10, 12, 14];
const MUNICIPALITY_ACTIVE = [10, 8, 12, 6, 11, 9, 14, 7, 12, 10];

/** The autumn term the whole fixture is built around. */
const TERM_START = "2026-08-10";
const CONSUMER_TERM_END = "2026-12-13";
/**
 * The school term's last day — one date for all twenty municipality clubs.
 *
 * That single shared date is the case the coming-up feed was redesigned around:
 * a term does not trickle to a close, so twenty rows all saying the same thing
 * on the same Friday is exactly the wall the cohort collapse exists to fold.
 */
const MUNICIPALITY_TERM_END = "2026-11-27";
/** The second wave of school clubs, starting with the new school term. */
const MUNICIPALITY_WAVE_TWO_START = "2026-09-07";
/** The first index of that second wave. */
const MUNICIPALITY_WAVE_TWO_FROM = 15;
/** Syysloma — the week the school clubs are closed. */
const AUTUMN_BREAK_WEEK = "2026-10-12";

/** Consumer clubs that have not opened yet, and when they do. */
const PENDING_CONSUMER: Readonly<Partial<Record<number, string>>> = {
  5: "2026-09-07",
  13: "2026-09-14",
  20: "2026-10-05",
};

function consumerClubs(): ProductSpec[] {
  return CONSUMER_CLUB_NAMES.map((name, index) => {
    const id = `consumer-club-${index + 1}`;
    const pendingStart = PENDING_CONSUMER[index];
    const seatCount = CONSUMER_SEATS[index % CONSUMER_SEATS.length];
    const primary = PRIMARY_WEEKDAYS[index % PRIMARY_WEEKDAYS.length];
    // Two clubs run at the weekend, which is the only way the Saturday and
    // Sunday rows ever carry anything — and seven rows whose last two are always
    // empty are five rows with a design flaw.
    const weekendWeekday = index === 22 ? 5 : index === 24 ? 6 : null;

    // Most consumer clubs meet twice a week; a fifth of them once. The mix is
    // what gives the week its density — a hundred-odd resolved sessions across
    // sixty products, peaking around twenty on a Wednesday, which is the load
    // the wrapping row has to stay legible under.
    const slots =
      weekendWeekday === null
        ? [
            slot(primary, index),
            ...(index % 5 === 4 ? [] : [slot(secondWeekday(primary), index + 3)]),
          ]
        : [slot(weekendWeekday, index), slot(primary, index + 1)];

    return {
      id,
      name,
      productType: "consumer_club",
      status: pendingStart === undefined ? "running" : "pending",
      startDate: pendingStart ?? TERM_START,
      // Most consumer clubs are open-ended subscriptions with no last day, so
      // they never appear on the coming-up feed's "ends" side at all.
      endDate: index % 4 === 1 ? CONSUMER_TERM_END : null,
      seatCount,
      activeCount: Math.min(
        CONSUMER_ACTIVE[index % CONSUMER_ACTIVE.length],
        seatCount,
      ),
      slots,
      breakWeeks: [],
    };
  });
}

function municipalityClubs(): ProductSpec[] {
  return MUNICIPALITY_CLUB_NAMES.map((name, index) => {
    const id = `municipality-club-${index + 1}`;
    const waveTwo = index >= MUNICIPALITY_WAVE_TWO_FROM;
    const seatCount = MUNICIPALITY_SEATS[index % MUNICIPALITY_SEATS.length];
    const primary = PRIMARY_WEEKDAYS[(index + 6) % PRIMARY_WEEKDAYS.length];

    return {
      id,
      name,
      productType: "municipality_club",
      status: waveTwo ? "pending" : "running",
      startDate: waveTwo ? MUNICIPALITY_WAVE_TWO_START : TERM_START,
      endDate: MUNICIPALITY_TERM_END,
      seatCount,
      activeCount: Math.min(
        MUNICIPALITY_ACTIVE[index % MUNICIPALITY_ACTIVE.length],
        seatCount,
      ),
      slots:
        index % 3 === 0
          ? [slot(primary, index), slot(secondWeekday(primary), index + 2)]
          : [slot(primary, index)],
      // Four of them carry the holiday break, which is enough to prove the
      // resolved week drops them and enough for the break line under it to stay
      // one readable sentence.
      breakWeeks: index < 4 ? [AUTUMN_BREAK_WEEK] : [],
    };
  });
}

/** Camps are authored one at a time — ten runs, ten different weeks. */
const CAMP_SPECS: readonly {
  name: string;
  start: string;
  end: string;
  seats: number;
  active: number;
  status: ProductStatus;
}[] = [
  {
    name: "Minecraft-leiri Helsinki",
    start: "2026-08-10",
    end: "2026-08-14",
    seats: 24,
    active: 24,
    status: "completed",
  },
  {
    name: "Roblox Studio -leiri Espoo",
    start: "2026-08-24",
    end: "2026-08-28",
    seats: 20,
    active: 17,
    status: "running",
  },
  {
    name: "Game Design -leiri Otaniemi",
    start: "2026-09-07",
    end: "2026-09-11",
    seats: 18,
    active: 11,
    status: "pending",
  },
  {
    name: "Fortnite-leiri Tapiola",
    start: "2026-09-28",
    end: "2026-10-02",
    seats: 20,
    active: 6,
    status: "pending",
  },
  {
    name: "Syyslomaleiri Kamppi",
    start: "2026-10-12",
    end: "2026-10-16",
    seats: 30,
    active: 22,
    status: "pending",
  },
  {
    name: "Minecraft Redstone -leiri Vantaa",
    start: "2026-10-12",
    end: "2026-10-16",
    seats: 18,
    active: 18,
    status: "pending",
  },
  {
    name: "Roblox-leiri Kirkkonummi",
    start: "2026-10-12",
    end: "2026-10-14",
    seats: 16,
    active: 9,
    status: "pending",
  },
  {
    name: "Esports-leiri Pasila",
    start: "2026-11-02",
    end: "2026-11-06",
    seats: 24,
    active: 13,
    status: "pending",
  },
  {
    name: "Minecraft-leiri Turku",
    start: "2026-11-16",
    end: "2026-11-20",
    seats: 20,
    active: 4,
    status: "pending",
  },
  {
    name: "Roblox Studio -leiri Tampere",
    start: "2026-12-21",
    end: "2026-12-23",
    seats: 16,
    active: 2,
    status: "pending",
  },
];

function camps(): ProductSpec[] {
  return CAMP_SPECS.map((spec, index) => ({
    id: `camp-${index + 1}`,
    name: spec.name,
    productType: "camp",
    status: spec.status,
    startDate: spec.start,
    endDate: spec.end,
    seatCount: spec.seats,
    activeCount: spec.active,
    // A camp runs every weekday of its week, which is what makes a camp week
    // visibly different from a club week: five rows gain the same green chip at
    // the same hour.
    slots: weekdaysBetween(spec.start, spec.end).map((weekday) => ({
      weekday,
      startTime: "10:00",
      durationMinutes: 180,
    })),
    breakWeeks: [],
  }));
}

/** Events are single dates — one slot each, on the weekday they fall on. */
const EVENT_SPECS: readonly {
  name: string;
  date: string;
  startTime: string;
  durationMinutes: number;
  seats: number | null;
  active: number;
  status: ProductStatus;
}[] = [
  {
    name: "LAN-ilta Kaapelitehdas",
    date: "2026-08-19",
    startTime: "17:00",
    durationMinutes: 240,
    seats: 60,
    active: 47,
    status: "running",
  },
  {
    name: "Perheiden peli-ilta Espoo",
    date: "2026-09-12",
    startTime: "13:00",
    durationMinutes: 180,
    seats: null,
    active: 82,
    status: "pending",
  },
  {
    name: "Minecraft-turnaus Helsinki",
    date: "2026-10-08",
    startTime: "16:00",
    durationMinutes: 240,
    seats: 48,
    active: 31,
    status: "pending",
  },
  {
    name: "Vanhempainilta: pelaaminen ja lapset",
    date: "2026-11-14",
    startTime: "18:00",
    durationMinutes: 90,
    seats: 40,
    active: 12,
    status: "pending",
  },
  {
    name: "Sogverse-avoimet ovet Tapiola",
    date: "2026-12-05",
    startTime: "12:00",
    durationMinutes: 240,
    seats: null,
    active: 5,
    status: "pending",
  },
];

function events(): ProductSpec[] {
  return EVENT_SPECS.map((spec, index) => ({
    id: `event-${index + 1}`,
    name: spec.name,
    productType: "event",
    status: spec.status,
    startDate: spec.date,
    endDate: spec.date,
    seatCount: spec.seats,
    activeCount: spec.active,
    slots: [
      {
        weekday: weekdayOf(spec.date),
        startTime: spec.startTime,
        durationMinutes: spec.durationMinutes,
      },
    ],
    breakWeeks: [],
  }));
}

/** The small platform: six products, nothing wrong with any of them. */
function quietCatalogue(): ProductSpec[] {
  return [
    {
      id: "consumer-club-1",
      name: "Minecraft-klubi Espoo",
      productType: "consumer_club",
      status: "running",
      startDate: TERM_START,
      endDate: null,
      seatCount: 12,
      activeCount: 9,
      slots: [
        { weekday: 1, startTime: "17:00", durationMinutes: 90 },
        { weekday: 3, startTime: "17:00", durationMinutes: 90 },
      ],
      breakWeeks: [],
    },
    {
      id: "consumer-club-2",
      name: "Roblox Studio -klubi Kamppi",
      productType: "consumer_club",
      status: "running",
      startDate: TERM_START,
      endDate: null,
      seatCount: 16,
      activeCount: 11,
      slots: [{ weekday: 2, startTime: "16:30", durationMinutes: 90 }],
      breakWeeks: [],
    },
    {
      id: "municipality-club-1",
      name: "Minecraft-kerho Tapiolan koulu",
      productType: "municipality_club",
      status: "running",
      startDate: TERM_START,
      endDate: MUNICIPALITY_TERM_END,
      seatCount: 10,
      activeCount: 10,
      slots: [{ weekday: 0, startTime: "15:00", durationMinutes: 60 }],
      breakWeeks: [AUTUMN_BREAK_WEEK],
    },
    {
      id: "municipality-club-2",
      name: "Pelikerho Leppävaaran koulu",
      productType: "municipality_club",
      status: "running",
      startDate: TERM_START,
      endDate: MUNICIPALITY_TERM_END,
      seatCount: 12,
      activeCount: 8,
      slots: [{ weekday: 4, startTime: "15:30", durationMinutes: 60 }],
      breakWeeks: [AUTUMN_BREAK_WEEK],
    },
    {
      id: "camp-1",
      name: "Roblox Studio -leiri Espoo",
      productType: "camp",
      status: "running",
      startDate: "2026-08-24",
      endDate: "2026-08-28",
      seatCount: 20,
      activeCount: 18,
      slots: weekdaysBetween("2026-08-24", "2026-08-28").map((weekday) => ({
        weekday,
        startTime: "10:00",
        durationMinutes: 180,
      })),
      breakWeeks: [],
    },
    {
      id: "event-1",
      name: "LAN-ilta Kaapelitehdas",
      productType: "event",
      status: "running",
      startDate: "2026-08-19",
      endDate: "2026-08-19",
      seatCount: 60,
      activeCount: 41,
      slots: [
        {
          weekday: weekdayOf("2026-08-19"),
          startTime: "17:00",
          durationMinutes: 240,
        },
      ],
      breakWeeks: [],
    },
  ];
}

// ---------------------------------------------------------------------------
// The attention queue
// ---------------------------------------------------------------------------

/**
 * What is wrong with each product that needs an admin.
 *
 * Authored as `(product, issue kinds)` pairs so the queue reads the way an admin
 * thinks — *this product, these problems* — rather than as ten category lists a
 * reader has to reassemble a product from. Twenty-one products across five kinds
 * of problem, deliberately uneven: three carry a stack of three, most carry one,
 * and two carry two group lines each, because a card whose only shape is "one
 * line" says nothing about how a card with several reads.
 */
const PRODUCT_ISSUE_SPECS: readonly {
  productId: string;
  issues: readonly { kind: ProductIssueKind; label: string }[];
}[] = [
  {
    productId: "consumer-club-1",
    issues: [
      { kind: "unassigned-gamers", label: "4 unassigned gamers" },
      { kind: "group-without-gedu", label: "Group Tiistai A has no gedu" },
      { kind: "missing-gedu-fee", label: "Gedu fee not set" },
    ],
  },
  {
    productId: "consumer-club-4",
    issues: [{ kind: "unassigned-gamers", label: "3 unassigned gamers" }],
  },
  {
    productId: "municipality-club-2",
    issues: [
      { kind: "unassigned-gamers", label: "3 unassigned gamers" },
      { kind: "group-without-gedu", label: "Group Kerho 1 has no gedu" },
    ],
  },
  {
    productId: "consumer-club-11",
    issues: [
      { kind: "unassigned-gamers", label: "2 unassigned gamers" },
      { kind: "waitlist-open-seats", label: "3 waitlisted · 8 seats open" },
    ],
  },
  {
    productId: "municipality-club-9",
    issues: [{ kind: "unassigned-gamers", label: "2 unassigned gamers" }],
  },
  {
    productId: "camp-2",
    issues: [
      { kind: "unassigned-gamers", label: "2 unassigned gamers" },
      { kind: "group-without-gedu", label: "Group Builders red has no gedu" },
    ],
  },
  {
    productId: "consumer-club-19",
    issues: [{ kind: "unassigned-gamers", label: "1 unassigned gamer" }],
  },
  {
    productId: "consumer-club-7",
    issues: [
      { kind: "group-without-gedu", label: "Group Keskiviikko B has no gedu" },
      { kind: "group-without-gedu", label: "Group Keskiviikko C has no gedu" },
    ],
  },
  {
    productId: "municipality-club-5",
    issues: [{ kind: "group-without-gedu", label: "Group Kerho 1 has no gedu" }],
  },
  {
    productId: "camp-5",
    issues: [
      { kind: "group-without-gedu", label: "Group Builders sininen has no gedu" },
      { kind: "missing-gedu-fee", label: "Gedu fee not set" },
    ],
  },
  {
    productId: "consumer-club-3",
    issues: [
      { kind: "waitlist-open-seats", label: "3 waitlisted · 4 seats open" },
    ],
  },
  {
    productId: "municipality-club-4",
    issues: [
      { kind: "waitlist-open-seats", label: "4 waitlisted · 4 seats open" },
    ],
  },
  {
    productId: "consumer-club-6",
    issues: [{ kind: "missing-gedu-fee", label: "Gedu fee not set" }],
  },
  {
    productId: "consumer-club-14",
    issues: [{ kind: "missing-gedu-fee", label: "Gedu fee not set" }],
  },
  {
    productId: "consumer-club-21",
    issues: [{ kind: "missing-gedu-fee", label: "Gedu fee not set" }],
  },
  {
    productId: "municipality-club-8",
    issues: [
      { kind: "missing-gedu-fee", label: "Gedu fee not set" },
      { kind: "missing-municipality-fee", label: "Municipality fee not set" },
    ],
  },
  {
    productId: "camp-4",
    issues: [{ kind: "missing-gedu-fee", label: "Gedu fee not set" }],
  },
  {
    productId: "event-3",
    issues: [{ kind: "missing-gedu-fee", label: "Gedu fee not set" }],
  },
  {
    productId: "municipality-club-13",
    issues: [
      { kind: "missing-municipality-fee", label: "Municipality fee not set" },
    ],
  },
  {
    productId: "municipality-club-16",
    issues: [
      { kind: "missing-municipality-fee", label: "Municipality fee not set" },
    ],
  },
  {
    productId: "municipality-club-19",
    issues: [
      { kind: "missing-municipality-fee", label: "Municipality fee not set" },
    ],
  },
];

/**
 * Gedus waiting on a decision, oldest wait last.
 *
 * Five, and spread from two days to two months on purpose: the wait is the only
 * thing distinguishing one row from another, and a queue where every row had
 * waited the same length would say nothing about whether the design makes a
 * two-month-old registration stand out from this morning's.
 */
const UNCERTIFIED_GEDUS: readonly UncertifiedGedu[] = [
  {
    id: PERSON_IDS.venlaSalminen,
    name: "Venla Salminen",
    registered: "registered 2 days ago",
  },
  {
    id: PERSON_IDS.topiasJarvinen,
    name: "Topias Järvinen",
    registered: "registered 5 days ago",
  },
  {
    id: PERSON_IDS.iidaLehtonen,
    name: "Iida Lehtonen",
    registered: "registered 9 days ago",
  },
  {
    id: PERSON_IDS.onniRantanen,
    name: "Onni Rantanen",
    registered: "registered 3 weeks ago",
  },
  {
    id: PERSON_IDS.helmiKoskinen,
    name: "Helmi Koskinen",
    registered: "registered 2 months ago",
  },
];

function buildProductAttention(
  byId: ReadonlyMap<string, ProductSpec>,
): ProductAttention[] {
  return PRODUCT_ISSUE_SPECS.map(({ productId, issues }) => {
    const spec = byId.get(productId);
    if (spec === undefined) {
      // A queue naming a product the catalogue does not hold would render a card
      // pointing nowhere, which is exactly the drift a fixture is supposed to
      // make impossible. Fail at build time instead.
      throw new Error(`Fixture references unknown product: ${productId}`);
    }
    return {
      productId: spec.id,
      name: spec.name,
      productType: spec.productType,
      href: ROUTES.admin.product(spec.productType, spec.id),
      issues: issues.map(
        (issue, index): ProductIssue => ({
          id: `${spec.id}-${issue.kind}-${index}`,
          kind: issue.kind,
          label: issue.label,
        }),
      ),
    };
  });
}

// ---------------------------------------------------------------------------
// Resolution
// ---------------------------------------------------------------------------

/**
 * Turn the catalogue into the weeks the schedule steps through.
 *
 * The whole range is resolved up front rather than on demand, because it is
 * eighteen weeks of arithmetic over sixty rows — cheap enough to do once, and
 * doing it once is what lets the body hold nothing but an index.
 */
function resolveWeeks(
  specs: readonly ProductSpec[],
  /** Product ids that appear somewhere in the attention queue. */
  flagged: ReadonlySet<string>,
): { weeks: ScheduleWeek[]; currentWeekIndex: number } {
  const weeks: ScheduleWeek[] = [];
  const firstMonday = addCalendarDays(mondayOf(TODAY), -7 * WEEKS_BEFORE);

  for (let offset = 0; offset <= WEEKS_BEFORE + WEEKS_AFTER; offset += 1) {
    const weekStart = addCalendarDays(firstMonday, 7 * offset);
    const chips: ScheduleChip[] = [];
    const onBreak: string[] = [];

    for (const spec of specs) {
      // A cancelled or completed product is history: it has no occurrences to
      // resolve, whatever its slots still say.
      if (spec.status === "cancelled" || spec.status === "completed") continue;

      const runsThisWeek = spec.slots.some((entry) =>
        withinRun(spec, addCalendarDays(weekStart, entry.weekday)),
      );
      if (!runsThisWeek) continue;

      if (spec.breakWeeks.includes(weekStart)) {
        onBreak.push(spec.name);
        continue;
      }

      for (const entry of spec.slots) {
        const date = addCalendarDays(weekStart, entry.weekday);
        if (!withinRun(spec, date)) continue;
        chips.push({
          id: `${spec.id}-${date}-${entry.startTime}`,
          productId: spec.id,
          productName: spec.name,
          productType: spec.productType,
          weekday: entry.weekday,
          startTime: entry.startTime,
          durationMinutes: entry.durationMinutes,
          activeCount: spec.activeCount,
          seatCount: spec.seatCount,
          needsAttention: flagged.has(spec.id),
          href: ROUTES.admin.product(spec.productType, spec.id),
        });
      }
    }

    weeks.push({ weekStart, chips, onBreak });
  }

  return { weeks, currentWeekIndex: WEEKS_BEFORE };
}

function withinRun(spec: ProductSpec, date: string): boolean {
  if (date < spec.startDate) return false;
  return spec.endDate === null || date <= spec.endDate;
}

/** Every weekday (0…6) a run covers, for a span of at most one week. */
function weekdaysBetween(start: string, end: string): number[] {
  const weekdays: number[] = [];
  let cursor = start;
  while (cursor <= end) {
    weekdays.push(weekdayOf(cursor));
    cursor = addCalendarDays(cursor, 1);
  }
  return weekdays;
}

/** Order the cohorts on one day take: what begins, what happens, what ends. */
const COMING_UP_KIND_ORDER: readonly ComingUpCohort["kind"][] = [
  "starts",
  "runs",
  "ends",
];

/**
 * Build the coming-up feed: one entry per milestone, grouped by date and then by
 * kind and product type.
 *
 * A single-date product gets its own kind rather than being called a "start".
 * An event that begins and ends on one evening does not *start* — it happens —
 * and a feed that says "LAN-ilta Kaapelitehdas starts" and then never mentions
 * it again is describing something other than what an event is.
 */
function buildComingUp(specs: readonly ProductSpec[]): ComingUpDay[] {
  const horizonEnd = monthsAfter(`${TODAY.slice(0, 7)}-01`, COMING_UP_MONTHS);
  const inHorizon = (date: string) => date >= TODAY && date < horizonEnd;

  const byDate = new Map<string, Map<string, ComingUpCohort>>();

  const add = (
    date: string,
    kind: ComingUpCohort["kind"],
    spec: ProductSpec,
  ) => {
    const cohortKey = `${kind}-${spec.productType}`;
    let day = byDate.get(date);
    if (day === undefined) {
      day = new Map<string, ComingUpCohort>();
      byDate.set(date, day);
    }
    const existing = day.get(cohortKey);
    const item: ComingUpItem = {
      id: spec.id,
      name: spec.name,
      href: ROUTES.admin.product(spec.productType, spec.id),
      activeCount: spec.activeCount,
      seatCount: spec.seatCount,
    };
    if (existing === undefined) {
      day.set(cohortKey, {
        id: `${date}-${cohortKey}`,
        kind,
        productType: spec.productType,
        items: [item],
      });
    } else {
      day.set(cohortKey, { ...existing, items: [...existing.items, item] });
    }
  };

  for (const spec of specs) {
    if (spec.status === "cancelled" || spec.status === "completed") continue;

    if (spec.endDate === spec.startDate) {
      if (inHorizon(spec.startDate)) add(spec.startDate, "runs", spec);
      continue;
    }
    if (inHorizon(spec.startDate)) add(spec.startDate, "starts", spec);
    if (spec.endDate !== null && inHorizon(spec.endDate)) {
      add(spec.endDate, "ends", spec);
    }
  }

  return [...byDate.entries()]
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([date, cohorts]) => ({
      date,
      cohorts: [...cohorts.values()].sort(compareCohorts),
    }));
}

function compareCohorts(a: ComingUpCohort, b: ComingUpCohort): number {
  const kindDelta =
    COMING_UP_KIND_ORDER.indexOf(a.kind) - COMING_UP_KIND_ORDER.indexOf(b.kind);
  if (kindDelta !== 0) return kindDelta;
  return (
    PRODUCT_TYPE_ORDER.indexOf(a.productType) -
    PRODUCT_TYPE_ORDER.indexOf(b.productType)
  );
}

// ---------------------------------------------------------------------------
// The fixture
// ---------------------------------------------------------------------------

export function buildAdminDashboardFixture(
  scenario: AdminDashboardScenario,
): AdminDashboardData {
  const quiet = scenario === "quiet";

  const specs = quiet
    ? quietCatalogue()
    : [...consumerClubs(), ...municipalityClubs(), ...camps(), ...events()];

  const byId = new Map(specs.map((spec) => [spec.id, spec]));
  const products = quiet ? [] : buildProductAttention(byId);

  // The dot on a schedule chip and the cards in the queue are the same fact, so
  // the set of flagged products is taken from the queue rather than listed twice.
  const flagged = new Set(products.map((product) => product.productId));

  const { weeks, currentWeekIndex } = resolveWeeks(specs, flagged);

  return {
    now: ADMIN_DASHBOARD_NOW,
    timeZone: ADMIN_DASHBOARD_TIMEZONE,
    products,
    uncertifiedGedus: quiet ? [] : UNCERTIFIED_GEDUS,
    users: quiet ? QUIET_USER_STATS : BUSY_USER_STATS,
    weeks,
    currentWeekIndex,
    comingUp: buildComingUp(specs),
  };
}

/**
 * Plausible platform numbers — one parent to roughly one and a half gamers, most
 * addresses verified, and rather more gedus registered than certified, which is
 * the whole reason the certification queue above exists.
 */
const BUSY_USER_STATS: AdminDashboardData["users"] = [
  { role: "customer", total: 214, verified: 191, certified: null },
  { role: "gamer", total: 342, verified: null, certified: null },
  { role: "gedu", total: 19, verified: 17, certified: 12 },
  { role: "admin", total: 4, verified: 4, certified: null },
];

const QUIET_USER_STATS: AdminDashboardData["users"] = [
  { role: "customer", total: 12, verified: 9, certified: null },
  { role: "gamer", total: 18, verified: null, certified: null },
  { role: "gedu", total: 3, verified: 3, certified: 3 },
  { role: "admin", total: 2, verified: 2, certified: null },
];

function slot(
  weekday: number,
  timeIndex: number,
): { weekday: number; startTime: string; durationMinutes: number } {
  return {
    weekday,
    startTime: CLUB_START_TIMES[timeIndex % CLUB_START_TIMES.length],
    durationMinutes: CLUB_DURATIONS[timeIndex % CLUB_DURATIONS.length],
  };
}
