import type { LocationType } from "@/types";

/**
 * The shape of the per-country location catalogs in this directory
 * (`fr.json`, `fi.json`), generated by `scripts/generate-location-catalogs.mjs`
 * from each country's official statistical classification.
 *
 * A catalog is the **exhaustive** list of a country's official administrative
 * divisions. The `locations` table, by contrast, holds only the rows something
 * actually references — a catalog entry becomes a row the first time an admin
 * picks it. So the catalog is what an admin browses and searches; the table is
 * what products, sites and gedu coverage point at.
 *
 * ## Why tuples
 *
 * France alone has 34,875 communes. The catalog is a static asset shipped to
 * the browser behind a dynamic import, so every repeated object key is paid for
 * 34,875 times. Positional tuples keep the payload roughly a third the size of
 * the equivalent `{ code, name, children }` objects, and the cost is one
 * destructure at the read site.
 */
export type CatalogNode = readonly [
  /** The official code in this country's classification (INSEE / Tilastokeskus). */
  code: string,
  /** The official name, in the country's own language, exactly as published. */
  name: string,
  /** Absent on leaf nodes. Present, and non-empty, on every level above. */
  children?: readonly CatalogNode[],
];

export interface LocationCatalog {
  /** ISO 3166-1 alpha-2, matching `locations.country_code`. */
  readonly country: string;
  /** Human-readable provenance, e.g. "INSEE Code officiel géographique 2026". */
  readonly source: string;
  /** The upstream release this was generated from, e.g. "2026". */
  readonly release: string;
  /** ISO date the generator last ran. */
  readonly generated: string;
  /**
   * What each depth of `tree` means, root first — the same `location_type`
   * values a materialized row gets. France is
   * `["region", "district", "municipality"]`; Finland skips `district` and is
   * `["region", "municipality"]`. Read the depth's type from here rather than
   * assuming a fixed depth: countries do not all use every level.
   */
  readonly levels: readonly LocationType[];
  /** Node count per depth, index-aligned with `levels`. Sanity/telemetry only. */
  readonly counts: readonly number[];
  /** Root-level nodes, sorted by name under the country's own collation. */
  readonly tree: readonly CatalogNode[];
}
